### ISSUE TITLE
Create image based volume fails

### ISSUE THREAD

**Issue by pandeyop** [JioCloud/puppet-rjil#326]
I find that the below tempest test is failing in all the environments:
tempest.api.volume.test_volumes_get.VolumesV2GetTest.test_volume_create_get_update_delete_from_image
ServerFault: Got server fault
Details: The server has either erred or is incapable of performing the requested operation.

I tried the test steps manually too:
cinder create --image-id ad181e83-f590-4842-803f-b101f2acb696 --display-name ompVol 1
ERROR: Internal Server Error (HTTP 500) (Request-ID: req-0b8a60dd-d418-4827-9fd1-e209d41304e7)
Note: The image used is a cirros image used in our environment.

I tried to check the logs for this request id and find there is a circular reference:
2015-01-16 08:17:12.718 3120 ERROR cinder.api.middleware.fault [req-0b8a60dd-d418-4827-9fd1-e209d41304e7 34f0f727edeb429eb9665e111aef3185 3b2ab3394f6b40ca88ee52a19ac96518 - - -] Caught error: Circular reference detected

**Comment by pandeyop** [comment]
Creating an image based volume works fine in devstack:
cinder create --image-id 51b893d4-f195-4ece-a1b0-32e4e0639a91 --display-name svol 1
All details about the created volume "svol" are available on doing a cinder-list.

**Comment by pandeyop** [comment]
This has been fixed through the below patch.
https://github.com/JioCloud/puppet-rjil/pull/375/
I can find the tempest test passing now:
tempest.api.volume.test_volumes_get.VolumesV2GetTest.test_volume_create_get_update_delete_from_image

**Comment by jaspreetw** [comment]
This issue still exists in production enviornment . 

cinder create --image-id bc9b8592-13f8-486a-b9d2-feaac0ca6bf2  --display-name imgVol 2
root@st7:/home/jas/tempest# cinder list
+--------------------------------------+--------+--------------+------+-------------+----------+-------------+
|                  ID                  | Status | Display Name | Size | Volume Type | Bootable | Attached to |
+--------------------------------------+--------+--------------+------+-------------+----------+-------------+
| 37ef3180-6028-490b-94ac-27644f71a137 | error  |    imgVol    |  2   |     None    |  false   |             |
+--------------------------------------+--------+--------------+------+-------------+----------+-------------+

**Comment by sorenh** [comment]
This is because Cirros is being uploaded as a qcow2. Other images will work fine.

**Comment by sorenh** [comment]
I'm not currently entirely comfortable allowing qcow2 to be converted on the fly. There are several security concerns involved in that process.

Just off the top of my head:
1) qcow2 can specify a backing store. This means it can specify another file that acts as its base. When used with qemu, apparmor makes sure that it doesn't get access to read data it's not supposed to (databases, password files, private keys, etc.), but plain qemu-img doesn't have the same protection.
2) qcow2 can be sparse. A qcow2 of just a few hundred kB can have a virtual size of several exabytes. I'm not sure if there are safeguards in place to prevent such an image from DOSing the volume backend.

**Comment by sorenh** [comment]
...so, essentially, we should document that qcow2 won't work and try to make it clear at the time of upload rather than at the time of volume creation.
